services:
  query_v2_1:
    environment:
      QDL_STABLE_TLS_CLIENT_CA_FILE: /stable-certs/query/client-ca-bundle.crt
      QDL_STABLE_REFERENCE_DATA_ENABLED: "true"
      QDL_STABLE_PROVIDER_ADMISSION_URL: http://rust_core:8300

  query_v2_2:
    environment:
      QDL_STABLE_TLS_CLIENT_CA_FILE: /stable-certs/query/client-ca-bundle.crt
      QDL_STABLE_REFERENCE_DATA_ENABLED: "true"
      QDL_STABLE_PROVIDER_ADMISSION_URL: http://rust_core:8300

  stream_v2_active:
    environment:
      QDL_STABLE_TLS_CLIENT_CA_FILE: /stable-certs/stream/client-ca-bundle.crt

  stream_v2_passive:
    environment:
      QDL_STABLE_TLS_CLIENT_CA_FILE: /stable-certs/stream/client-ca-bundle.crt
