[package]
name = "qdl-core"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
prost.workspace = true
qdl-contracts = { path = "../qdl-contracts", version = "=0.1.0" }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
